<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(1,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[3]=array(1,1,1,'5LyB5Lia5paH5YyW');
$cfg_Cs[4]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[5]=array(4,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[6]=array(4,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[7]=array(0,1,1,'5a6i5oi35qGI5L6L');
$cfg_Cs[8]=array(7,1,1,'572R56uZ5bu66K6+');
$cfg_Cs[9]=array(7,1,1,'5bqU55So5byA5Y+R');
$cfg_Cs[10]=array(7,1,1,'572R57uc6JCl6ZSA');
$cfg_Cs[11]=array(0,1,1,'5oqA5pyv5pSv5oyB');
$cfg_Cs[12]=array(0,1,1,'5Zyo57q/55WZ6KiA');
$cfg_Cs[13]=array(0,1,1,'6IGU57O75oiR5Lus');
?>