<?php
$z[0]=Array("field","",126,145);
$z[0][4]['name']="title";
$z[1]=Array("global","",146,172);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",213,242);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",282,340);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1116,1151);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channelartlist","\r\n            <li {dede:field name='currentstyle'/}><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n            ",1318,1526);
$z[5][4]['type']="son";
$z[5][4]['typeid']="1";
$z[6]=Array("global","",1597,1618);
$z[6][4]['name']="cfg_qq";
$z[7]=Array("arclist","\r\n     <li><span>[field:pubdate  function='strftime(\"%m-%d\",@me)'/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n    ",2030,2221);
$z[7][4]['row']="6";
$z[7][4]['titlelen']="24";
$z[7][4]['typeid']="5";
$z[8]=Array("arclist","\r\n     <li><span>[field:pubdate  function='strftime(\"%m-%d\",@me)'/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n    ",2263,2454);
$z[8][4]['row']="6";
$z[8][4]['titlelen']="24";
$z[8][4]['typeid']="6";
$z[9]=Array("field","",2575,2597);
$z[9][4]['name']="position";
$z[10]=Array("field","",2649,2670);
$z[10][4]['name']="content";
$z[11]=Array("include","",2710,2745);
$z[11][4]['filename']="foot.htm";

?>