<?php
$z[0]=Array("channelartlist","\r\n                <li><a href=\"{dede:field name='typeurl'/}\" {dede:field name='currentstyle'/}>{dede:field name='typename'/}</a>\r\n                 <ul>\r\n                    {dede:channel type='son' noself='yes'}\r\n                    <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                    {/dede:channel}\r\n                 </ul>\r\n                </li>\r\n                ",219,675);
$z[0][4]['row']="20";
$z[0][4]['typeid']="top";

?>