<?php
$z[0]=Array("global","",126,152);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",196,226);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",263,290);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("channelartlist","\r\n                <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n                 <ul>\r\n                    {dede:channel type='son' noself='yes'}\r\n                    <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                    {/dede:channel}\r\n                 </ul>\r\n                </li>\r\n                ",1305,1802);
$z[3][4]['row']="20";
$z[3][4]['typeid']="top";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='active'>~typename~</a></li>";
$z[4]=Array("arclist","\r\n    <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"100\" height=\"90\">\r\n     <div class=\"bbar\"></div>\r\n        <p>[field:title/]</p></a>\r\n     </li>\r\n	",2616,2859);
$z[4][4]['row']="3";
$z[4][4]['titlelen']="36";
$z[4][4]['typeid']="7";
$z[4][4]['type']="image";
$z[5]=Array("include","",3166,3201);
$z[5][4]['filename']="foot.htm";

?>