<?php
$z[0]=Array("field","",124,143);
$z[0][4]['name']="title";
$z[1]=Array("global","",144,170);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",211,240);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",280,338);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1123,1158);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channelartlist","\r\n      <li {dede:field name='currentstyle'/}><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n      ",1282,1478);
$z[5][4]['type']="son";
$z[5][4]['typeid']="4";
$z[6]=Array("global","",1536,1557);
$z[6][4]['name']="cfg_qq";
$z[7]=Array("arclist","\r\n     <li><span>[field:pubdate  function='strftime(\"%m-%d\",@me)'/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n    ",1874,2065);
$z[7][4]['row']="6";
$z[7][4]['titlelen']="24";
$z[7][4]['typeid']="5";
$z[8]=Array("arclist","\r\n     <li><span>[field:pubdate  function='strftime(\"%m-%d\",@me)'/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n    ",2107,2298);
$z[8][4]['row']="6";
$z[8][4]['titlelen']="24";
$z[8][4]['typeid']="6";
$z[9]=Array("field","",2431,2453);
$z[9][4]['name']="position";
$z[10]=Array("list","\r\n        <li><span class=\"date\">[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span><a href=\"[field:arcurl/]\" title=\"\"><span>> </span>[field:title/]</a></li>\r\n        ",2523,2749);
$z[10][4]['pagesize']="10";
$z[10][4]['titlelen']="36";
$z[11]=Array("pagelist","",2819,2885);
$z[11][4]['listitem']="index,end,pre,next,pageno";
$z[11][4]['listsize']="7";
$z[12]=Array("include","",2919,2954);
$z[12][4]['filename']="foot.htm";

?>