<?php
$z[0]=Array("field","",124,143);
$z[0][4]['name']="title";
$z[1]=Array("global","",144,170);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",211,240);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",280,338);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1135,1170);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channelartlist","\r\n      <li {dede:field name='currentstyle'/}><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n      ",1295,1491);
$z[5][4]['type']="son";
$z[5][4]['typeid']="7";
$z[6]=Array("global","",1549,1570);
$z[6][4]['name']="cfg_qq";
$z[7]=Array("arclist","\r\n     <li><span>[field:pubdate  function='strftime(\"%m-%d\",@me)'/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n    ",1871,2062);
$z[7][4]['row']="6";
$z[7][4]['titlelen']="24";
$z[7][4]['typeid']="5";
$z[8]=Array("arclist","\r\n     <li><span>[field:pubdate  function='strftime(\"%m-%d\",@me)'/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n    ",2104,2295);
$z[8][4]['row']="6";
$z[8][4]['titlelen']="24";
$z[8][4]['typeid']="6";
$z[9]=Array("field","",2428,2450);
$z[9][4]['name']="position";
$z[10]=Array("list","\r\n        <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"305\" height=\"160\"></a>\r\n          <p>[field:title/]</p>\r\n        </li>\r\n        ",2527,2731);
$z[10][4]['pagesize']="6";
$z[10][4]['titlelen']="36";
$z[11]=Array("pagelist","",2794,2860);
$z[11][4]['listitem']="index,end,pre,next,pageno";
$z[11][4]['listsize']="7";
$z[12]=Array("include","",2898,2933);
$z[12][4]['filename']="foot.htm";

?>